url: http://bikethru.com
permalink: /:title.html
pygments: true
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]

# presonal config
title: BikeThru
comments: duoshuo

author:
  name: popfeng
  nickname: 树袋大熊
  email: popfeng@yeah.net
  site: http://bikethru.com

seo: 
  keywords: popfeng 树袋大熊 看那些麦子
  description: 树袋大熊的博客

config:
  js_dir:
  img_dir:
  css_dir:
